let a = 10
let b = 2
let c

try {
    
    console.log("Soma: ", a + c)

} catch (error) {

    console.log("Erro: ", error)

}